// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/jcsvwinston/nucleus/pkg/openapi"
)

// The TypeScript client (A10, the arc's gate). Generated here, in Go, from
// the document the application serves: one file, no dependency — the types
// of every component schema, an error class that reads the framework's
// envelope and problem+json alike, and a Client with one method per
// operation, named after its operationId, typed by its parameters, body and
// success response. It speaks fetch, so the same file runs in a browser, in
// Node 18+ and in Deno.

// generateTypeScriptClient renders the client for doc.
func generateTypeScriptClient(doc *openapi.Document) (string, error) {
	g := &tsGen{doc: doc}
	return g.render()
}

type tsGen struct {
	doc *openapi.Document
	b   strings.Builder
}

func (g *tsGen) line(format string, args ...any) {
	fmt.Fprintf(&g.b, format, args...)
	g.b.WriteByte('\n')
}

// tsOperation is one operation as the client method sees it.
type tsOperation struct {
	method, path, name string
	op                 *openapi.Operation
}

func (g *tsGen) operations() []tsOperation {
	var ops []tsOperation
	paths := make([]string, 0, len(g.doc.Paths))
	for p := range g.doc.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	used := map[string]int{}
	for _, p := range paths {
		for _, m := range []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete} {
			op := g.doc.Paths[p].Operation(m)
			if op == nil {
				continue
			}
			name := tsIdentifier(op.OperationID)
			if name == "" {
				name = tsIdentifier(strings.ToLower(m) + "_" + p)
			}
			name = lowerFirstRune(name)
			used[name]++
			if n := used[name]; n > 1 {
				name += strconv.Itoa(n)
			}
			ops = append(ops, tsOperation{method: m, path: p, name: name, op: op})
		}
	}
	return ops
}

func (g *tsGen) render() (string, error) {
	title := g.doc.Info.Title
	if title == "" {
		title = "API"
	}
	g.line("// %s %s — TypeScript client generated by `nucleus openapi --client typescript`", title, g.doc.Info.Version)
	g.line("// from the application's OpenAPI document. Do not edit: regenerate it.")
	g.line("")

	names := make([]string, 0, len(g.doc.Components.Schemas))
	for n := range g.doc.Components.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		s := g.doc.Components.Schemas[n]
		if s.Description != "" {
			g.line("/** %s */", tsComment(s.Description))
		}
		if s.Type == "object" && s.Ref == "" && s.AdditionalProperties == nil && !s.Nullable {
			g.line("export interface %s %s", tsIdentifier(n), g.objectType(s, ""))
		} else {
			g.line("export type %s = %s;", tsIdentifier(n), g.typeOf(s, ""))
		}
		g.line("")
	}

	g.b.WriteString(tsRuntime)
	g.line("")
	g.line("export class Client {")
	g.line("  private readonly options: ClientOptions;")
	g.line("")
	g.line("  constructor(options: ClientOptions) {")
	g.line("    this.options = options;")
	g.line("  }")
	for _, o := range g.operations() {
		g.line("")
		g.method(o)
	}
	g.line("")
	g.line("  private async send<T>(method: string, path: string, query: Record<string, unknown> | undefined, headers: Record<string, unknown> | undefined, body: unknown): Promise<T> {")
	g.line("    return request<T>(this.options, method, path, query, headers, body);")
	g.line("  }")
	g.line("}")
	return g.b.String(), nil
}

// method renders one operation: path parameters first, in path order,
// then the body, then an object of the query and header parameters
// (optional when none of them is required).
func (g *tsGen) method(o tsOperation) {
	op := o.op
	var pathParams, others []openapi.Parameter
	for _, p := range op.Parameters {
		if p.In == "path" {
			pathParams = append(pathParams, p)
		} else if p.In == "query" || p.In == "header" {
			others = append(others, p)
		}
	}
	// Path parameters in the order the path names them.
	order := map[string]int{}
	for i, seg := range strings.Split(o.path, "/") {
		if strings.HasPrefix(seg, "{") {
			order[strings.Trim(seg, "{}")] = i
		}
	}
	sort.SliceStable(pathParams, func(i, j int) bool { return order[pathParams[i].Name] < order[pathParams[j].Name] })

	var args []string
	for _, p := range pathParams {
		args = append(args, fmt.Sprintf("%s: %s", tsIdentifier(lowerFirstRune(p.Name)), g.paramType(p.Schema)))
	}
	hasBody := op.RequestBody != nil && len(op.RequestBody.Content) > 0
	if hasBody {
		bodyType := "unknown"
		if mt, ok := op.RequestBody.Content["application/json"]; ok {
			bodyType = g.typeOf(mt.Schema, "  ")
		}
		opt := ""
		if !op.RequestBody.Required {
			opt = "?"
		}
		args = append(args, fmt.Sprintf("body%s: %s", opt, bodyType))
	}
	if len(others) > 0 {
		required := false
		var fields []string
		for _, p := range others {
			q := ""
			if !p.Required {
				q = "?"
			} else {
				required = true
			}
			fields = append(fields, fmt.Sprintf("%s%s: %s", tsKey(p.Name), q, g.paramType(p.Schema)))
		}
		opt := "?"
		if required {
			opt = ""
		}
		args = append(args, fmt.Sprintf("params%s: { %s }", opt, strings.Join(fields, "; ")))
	}

	result := g.successType(op)
	doc := strings.ToUpper(o.method) + " " + o.path
	if op.Summary != "" {
		doc += " — " + op.Summary
	}
	g.line("  /** %s */", tsComment(doc))
	g.line("  async %s(%s): Promise<%s> {", o.name, strings.Join(args, ", "), result)

	pathExpr := "`" + o.path + "`"
	for _, p := range pathParams {
		pathExpr = strings.ReplaceAll(pathExpr, "{"+p.Name+"}", "${encodeURIComponent(String("+tsIdentifier(lowerFirstRune(p.Name))+"))}")
	}
	query, headers := "undefined", "undefined"
	var qs, hs []string
	for _, p := range others {
		access := "params?." + tsAccess(p.Name)
		if p.In == "query" {
			qs = append(qs, fmt.Sprintf("%s: %s", tsKey(p.Name), access))
		} else {
			hs = append(hs, fmt.Sprintf("%s: %s", tsKey(p.Name), access))
		}
	}
	if len(qs) > 0 {
		query = "{ " + strings.Join(qs, ", ") + " }"
	}
	if len(hs) > 0 {
		headers = "{ " + strings.Join(hs, ", ") + " }"
	}
	body := "undefined"
	if hasBody {
		body = "body"
	}
	g.line("    return this.send<%s>(%q, %s, %s, %s, %s);", result, o.method, pathExpr, query, headers, body)
	g.line("  }")
}

// successType is the type of the lowest declared 2xx response with a JSON
// body; void when the success response has none; unknown when the
// operation declares no success response (a plain handler).
func (g *tsGen) successType(op *openapi.Operation) string {
	var codes []string
	for code := range op.Responses {
		if strings.HasPrefix(code, "2") {
			codes = append(codes, code)
		}
	}
	sort.Strings(codes)
	for _, code := range codes {
		r := op.Responses[code]
		if mt, ok := r.Content["application/json"]; ok {
			return g.typeOf(mt.Schema, "  ")
		}
		if len(r.Content) == 0 {
			return "void"
		}
	}
	return "unknown"
}

func (g *tsGen) paramType(s openapi.Schema) string {
	t := g.typeOf(s, "")
	if t == "unknown" {
		return "string"
	}
	return t
}

// typeOf renders a schema as a TypeScript type; indent is the indentation
// of the line the type starts on, for nested object literals.
func (g *tsGen) typeOf(s openapi.Schema, indent string) string {
	if s.Ref != "" {
		name := strings.TrimPrefix(s.Ref, "#/components/schemas/")
		return tsIdentifier(name)
	}
	var t string
	switch {
	case len(s.Enum) > 0:
		lits := make([]string, len(s.Enum))
		for i, e := range s.Enum {
			lits[i] = tsLiteral(e)
		}
		t = strings.Join(lits, " | ")
	case s.Type == "string":
		t = "string"
	case s.Type == "integer" || s.Type == "number":
		t = "number"
	case s.Type == "boolean":
		t = "boolean"
	case s.Type == "array":
		item := "unknown"
		if s.Items != nil {
			item = g.typeOf(*s.Items, indent)
		}
		if strings.ContainsAny(item, " |&") {
			item = "(" + item + ")"
		}
		t = item + "[]"
	case s.Type == "object" || len(s.Properties) > 0:
		switch {
		case len(s.Properties) > 0:
			t = g.objectType(s, indent)
		case s.AdditionalProperties != nil:
			t = "Record<string, " + g.typeOf(*s.AdditionalProperties, indent) + ">"
		default:
			t = "Record<string, unknown>"
		}
	default:
		t = "unknown"
	}
	if s.Nullable {
		t += " | null"
	}
	return t
}

func (g *tsGen) objectType(s openapi.Schema, indent string) string {
	if len(s.Properties) == 0 {
		return "{}"
	}
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	names := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString("{\n")
	for _, n := range names {
		p := s.Properties[n]
		if p.Description != "" {
			fmt.Fprintf(&b, "%s  /** %s */\n", indent, tsComment(p.Description))
		}
		q := "?"
		if required[n] {
			q = ""
		}
		fmt.Fprintf(&b, "%s  %s%s: %s;\n", indent, tsKey(n), q, g.typeOf(p, indent+"  "))
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(&b, "%s  [key: string]: unknown;\n", indent)
	}
	b.WriteString(indent + "}")
	return b.String()
}

// tsIdentifier turns a name into a TypeScript identifier: letters, digits,
// _ and $; separators become word breaks (list_articles → listArticles).
func tsIdentifier(s string) string {
	var b strings.Builder
	upper := false
	for i, r := range s {
		switch {
		case unicode.IsLetter(r) || r == '_' || r == '$' || (unicode.IsDigit(r) && i > 0):
			if upper && b.Len() > 0 {
				r = unicode.ToUpper(r)
			}
			upper = false
			b.WriteRune(r)
		case unicode.IsDigit(r):
			b.WriteRune('_')
			b.WriteRune(r)
		default:
			upper = true
		}
	}
	out := b.String()
	if tsReserved[out] {
		out += "_"
	}
	return out
}

var tsReserved = map[string]bool{
	"break": true, "case": true, "catch": true, "class": true, "const": true, "continue": true,
	"debugger": true, "default": true, "delete": true, "do": true, "else": true, "enum": true,
	"export": true, "extends": true, "false": true, "finally": true, "for": true, "function": true,
	"if": true, "import": true, "in": true, "instanceof": true, "new": true, "null": true,
	"return": true, "super": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true, "while": true, "with": true,
	"interface": true, "type": true, "let": true, "static": true, "yield": true, "await": true,
}

func lowerFirstRune(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

var tsPlainKey = func(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if !(unicode.IsLetter(r) || r == '_' || r == '$' || (i > 0 && unicode.IsDigit(r))) {
			return false
		}
	}
	return true
}

// tsKey writes a property name, quoted when it is not an identifier.
func tsKey(s string) string {
	if tsPlainKey(s) {
		return s
	}
	return strconv.Quote(s)
}

// tsAccess is the expression that reads property s of an object.
func tsAccess(s string) string {
	if tsPlainKey(s) {
		return s
	}
	return "[" + strconv.Quote(s) + "]"
}

func tsLiteral(v any) string {
	switch x := v.(type) {
	case string:
		return strconv.Quote(x)
	case bool:
		return strconv.FormatBool(x)
	case nil:
		return "null"
	}
	return fmt.Sprint(v)
}

func tsComment(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "*/", "* /"), "\n", " ")
}

// tsRuntime is the part of the client that does not depend on the
// document: the options, the error and the one request function every
// method calls.
const tsRuntime = `export interface ClientOptions {
  /** The application's origin, e.g. "http://localhost:8080". */
  baseUrl: string;
  /** A bearer token, or a function that returns the current one. */
  token?: string | (() => string | undefined);
  /** Headers sent with every request. */
  headers?: Record<string, string>;
  /** The fetch to use; the global one by default. */
  fetch?: typeof fetch;
}

/**
 * ApiError is what a method throws when the application answers outside
 * 2xx. code and message are read from the framework's error envelope
 * ({"error": {"code", "message", "details"}}) or from problem+json
 * (RFC 9457), whichever the application answered with.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: unknown;

  constructor(status: number, body: unknown) {
    const envelope = (body as { error?: { code?: string; message?: string } } | null)?.error;
    const problem = body as { title?: string; detail?: string; code?: string } | null;
    const code = envelope?.code ?? problem?.code ?? String(status);
    const message = envelope?.message ?? problem?.detail ?? problem?.title ?? "HTTP " + status;
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
    this.body = body;
  }
}

async function request<T>(
  options: ClientOptions,
  method: string,
  path: string,
  query: Record<string, unknown> | undefined,
  headers: Record<string, unknown> | undefined,
  body: unknown,
): Promise<T> {
  const url = new URL(path, options.baseUrl.endsWith("/") ? options.baseUrl : options.baseUrl + "/");
  for (const [key, value] of Object.entries(query ?? {})) {
    if (value === undefined || value === null) continue;
    for (const v of Array.isArray(value) ? value : [value]) url.searchParams.append(key, String(v));
  }
  const sent: Record<string, string> = { Accept: "application/json", ...(options.headers ?? {}) };
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (value !== undefined && value !== null) sent[key] = String(value);
  }
  const token = typeof options.token === "function" ? options.token() : options.token;
  if (token) sent["Authorization"] = "Bearer " + token;
  let payload: string | undefined;
  if (body !== undefined) {
    sent["Content-Type"] = "application/json";
    payload = JSON.stringify(body);
  }
  const res = await (options.fetch ?? fetch)(url, { method, headers: sent, body: payload });
  const text = await res.text();
  const type = res.headers.get("Content-Type") ?? "";
  const parsed: unknown = text !== "" && type.includes("json") ? JSON.parse(text) : text === "" ? undefined : text;
  if (!res.ok) throw new ApiError(res.status, parsed);
  return parsed as T;
}
`
