// Code generated by Quark CLI. DO NOT EDIT.
package models

type EventUsers struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (EventUsers) TableName() string {
	return "event_users"
}
