// Code generated by Quark CLI. DO NOT EDIT.
package models

type Logs struct {
	ID int `db:"id" pk:"true" json:"id"`
	Msg *string `db:"msg" json:"msg"`
}

func (Logs) TableName() string {
	return "logs"
}
