// Code generated by Quark CLI. DO NOT EDIT.
package models

import (
	"time"
)

type Posts struct {
	ID int `db:"id" pk:"true" json:"id"`
	Title *string `db:"title" json:"title"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

func (Posts) TableName() string {
	return "posts"
}
