// Code generated by Quark CLI. DO NOT EDIT.
package models

type QBUsers struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
	Age *int `db:"age" json:"age"`
	City *string `db:"city" json:"city"`
}

func (QBUsers) TableName() string {
	return "q_b_users"
}
