// Code generated by Quark CLI. DO NOT EDIT.
package models

type RawTest struct {
	ID *int `db:"id" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (RawTest) TableName() string {
	return "raw_test"
}
