// Code generated by Quark CLI. DO NOT EDIT.
package models

type StressRecords struct {
	ID int `db:"id" pk:"true" json:"id"`
	Data *string `db:"data" json:"data"`
	Value *int `db:"value" json:"value"`
}

func (StressRecords) TableName() string {
	return "stress_records"
}
