// Code generated by Quark CLI. DO NOT EDIT.
package models

type SuiteUsers struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
	Email *string `db:"email" json:"email"`
}

func (SuiteUsers) TableName() string {
	return "suite_users"
}
