// Code generated by Quark CLI. DO NOT EDIT.
package models

type TenantDatas struct {
	ID int `db:"id" pk:"true" json:"id"`
	TenantID *string `db:"tenant_id" json:"tenant_id"`
	Value *string `db:"value" json:"value"`
}

func (TenantDatas) TableName() string {
	return "tenant_datas"
}
