// Code generated by Quark CLI. DO NOT EDIT.
package models

type TxUsers struct {
	ID int `db:"id" pk:"true" json:"id"`
	Name *string `db:"name" json:"name"`
}

func (TxUsers) TableName() string {
	return "tx_users"
}
