// Copyright 2026 jcsvwinston
// SPDX-License-Identifier: Apache-2.0

// QCD-FW-11 side note, decided explicitly: the API baseline only failed on
// REMOVALS, so v1.9.0's new exported symbols (app.WithTemplateFuncs,
// app.WithTemplates, …) shipped without regenerating
// baseline/api_exported_symbols.txt — and every external consumer deriving
// coverage denominators from that file undercounts the public surface.
// Additions now must regenerate the baseline in the SAME change:
//
//	NUCLEUS_UPDATE_CONTRACT_BASELINE=1 go test ./contracts/ -run APIExportedSymbols
package contracts

import (
	"os"
	"sort"
	"strings"
	"testing"
)

func TestContractFreeze_APIExportedSymbols_NoUnlistedAdditions(t *testing.T) {
	currentLines := stableAPISymbolBaselineLines(t)
	if os.Getenv("NUCLEUS_UPDATE_CONTRACT_BASELINE") == "1" {
		t.Skip("baseline regenerated by the NoRemovals test in this run")
	}

	baseline := toSet(readBaselineLines(t, "baseline", "api_exported_symbols.txt"))

	added := make([]string, 0)
	for _, symbol := range currentLines {
		if _, ok := baseline[symbol]; !ok {
			added = append(added, symbol)
		}
	}
	sort.Strings(added)
	if len(added) > 0 {
		t.Fatalf("exported API symbols not listed in the frozen baseline (regenerate it in the same change: NUCLEUS_UPDATE_CONTRACT_BASELINE=1 go test ./contracts/ -run APIExportedSymbols):\n  %s", strings.Join(added, "\n  "))
	}
}
