package model

import (
	"fmt"
	"strings"
)

// BuildOracleMigrationScaffold renders deterministic CREATE/DROP
// migration SQL from extracted model metadata, in Oracle (PL/SQL)
// dialect.
//
// Differences from the Postgres scaffold:
//
//   - Identifiers are emitted UNQUOTED (ADR-011). Oracle folds unquoted
//     identifiers to upper case at parse time, which is the convention the
//     rest of the framework's Oracle path relies on (the CRUD layer emits
//     bare identifiers, the migrations bootstrap creates unquoted tables, and
//     introspection matches via `UPPER(...)`). Quoting would create
//     case-sensitive lower-case tables those layers could not resolve.
//   - Auto-increment PK uses `NUMBER GENERATED BY DEFAULT AS IDENTITY
//     PRIMARY KEY` (Oracle 12c+).
//   - Type mapping: `NUMBER(1)` (booleans — Oracle has no native
//     BOOLEAN before 23c), `BLOB` ([]byte), `TIMESTAMP(6) WITH TIME
//     ZONE` (time.Time), `BINARY_DOUBLE` (float64), `BINARY_FLOAT`
//     (float32), `NUMBER(10)` / `NUMBER(19)` (int / int64),
//     `VARCHAR2(4000)` (strings; the maximum without `MAX_STRING_SIZE
//     = EXTENDED`).
//   - Oracle has no `CREATE TABLE IF NOT EXISTS`. Every CREATE is
//     wrapped in a PL/SQL block that swallows ORA-00955 ("name is
//     already used by an existing object"), the same pattern used by
//     the migrations-table bootstrap in `pkg/db.migrate.go`.
//   - Index creation is also wrapped in a PL/SQL block swallowing
//     ORA-00955.
//   - DROP TABLE is wrapped in a PL/SQL block swallowing ORA-00942
//     ("table or view does not exist").
//   - DROP INDEX is wrapped in a PL/SQL block swallowing ORA-01418
//     ("specified index does not exist").
//
// Targets Oracle 12.2 or newer (longer identifier limit + IDENTITY
// columns). Earlier versions need sequence-based primary keys and a
// 30-character identifier budget.
func BuildOracleMigrationScaffold(meta *ModelMeta) (string, string, error) {
	if meta == nil {
		return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: meta is nil")
	}

	table := strings.TrimSpace(meta.Table)
	if !isValidIdentifierLike(table) {
		return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: invalid table name %q", table)
	}
	if len(meta.Fields) == 0 {
		return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: model %s has no fields", meta.Name)
	}

	columnDefs := make([]string, 0, len(meta.Fields)+len(meta.ForeignKeys))
	for _, f := range meta.Fields {
		column := strings.TrimSpace(f.Column)
		if column == "" {
			column = toSnakeCase(f.Name)
		}
		if !isValidIdentifierLike(column) {
			return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: invalid column %q in field %s", column, f.Name)
		}

		var def string
		if f.IsPK {
			if oracleAutoIncrementPKType(f.GoType) {
				def = oracleIdentifier(column) + " NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
			} else {
				def = oracleIdentifier(column) + " " + oracleTypeForField(f) + " PRIMARY KEY"
			}
		} else {
			def = oracleIdentifier(column) + " " + oracleTypeForField(f)
			if f.IsRequired {
				def += " NOT NULL"
			}
		}
		columnDefs = append(columnDefs, def)
	}

	seenConstraints := map[string]struct{}{}
	for _, fk := range meta.ForeignKeys {
		column := strings.TrimSpace(fk.Column)
		foreignTable := strings.TrimSpace(fk.ForeignTable)
		foreignColumn := strings.TrimSpace(fk.ForeignColumn)

		if column == "" || foreignTable == "" {
			continue
		}
		if foreignColumn == "" {
			foreignColumn = "id"
		}
		if !isValidIdentifierLike(column) || !isValidIdentifierLike(foreignTable) || !isValidIdentifierLike(foreignColumn) {
			return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: invalid foreign key identifiers for column %q", column)
		}

		constraintName := deterministicForeignKeyName(table, column, foreignTable, foreignColumn)
		if _, exists := seenConstraints[constraintName]; exists {
			continue
		}
		seenConstraints[constraintName] = struct{}{}

		columnDefs = append(columnDefs,
			fmt.Sprintf(
				"CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
				oracleIdentifier(constraintName),
				oracleIdentifier(column),
				oracleIdentifier(foreignTable),
				oracleIdentifier(foreignColumn),
			),
		)
	}

	createTable := &strings.Builder{}
	createTable.WriteString("CREATE TABLE ")
	createTable.WriteString(oracleIdentifier(table))
	createTable.WriteString(" (\n")
	for i, def := range columnDefs {
		sep := ","
		if i == len(columnDefs)-1 {
			sep = ""
		}
		createTable.WriteString("\t")
		createTable.WriteString(def)
		createTable.WriteString(sep)
		createTable.WriteString("\n")
	}
	createTable.WriteString(")")

	up := &strings.Builder{}
	writeOraclePLSQLBlock(up, createTable.String(), "-955", "table already exists")

	indexNames := make([]string, 0, len(meta.Indexes))
	for _, idx := range meta.Indexes {
		if len(idx.Columns) == 0 {
			continue
		}
		name := strings.TrimSpace(idx.Name)
		if name == "" {
			name = buildDefaultIndexName(table, idx.Columns[0], idx.Unique)
		}
		if !isValidIdentifierLike(name) {
			return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: invalid index name %q", name)
		}
		quotedCols := make([]string, 0, len(idx.Columns))
		for _, col := range idx.Columns {
			col = strings.TrimSpace(col)
			if !isValidIdentifierLike(col) {
				return "", "", fmt.Errorf("model.BuildOracleMigrationScaffold: invalid index column %q for index %q", col, name)
			}
			quotedCols = append(quotedCols, oracleIdentifier(col))
		}
		prefix := "CREATE INDEX"
		if idx.Unique {
			prefix = "CREATE UNIQUE INDEX"
		}
		stmt := fmt.Sprintf("%s %s ON %s (%s)", prefix, oracleIdentifier(name), oracleIdentifier(table), strings.Join(quotedCols, ", "))
		writeOraclePLSQLBlock(up, stmt, "-955", "index already exists")
		indexNames = append(indexNames, name)
	}

	down := &strings.Builder{}
	for i := len(indexNames) - 1; i >= 0; i-- {
		writeOraclePLSQLBlock(down, "DROP INDEX "+oracleIdentifier(indexNames[i]), "-1418", "specified index does not exist")
	}
	writeOraclePLSQLBlock(down, "DROP TABLE "+oracleIdentifier(table), "-942", "table or view does not exist")

	return up.String(), down.String(), nil
}

// writeOraclePLSQLBlock emits a PL/SQL block that runs `stmt` via
// EXECUTE IMMEDIATE and swallows the specified SQLCODE. Used to fake
// `IF [NOT] EXISTS` semantics that Oracle does not natively support.
//
// The `note` argument lands in a comment for operator-facing clarity.
//
// The block deliberately does NOT emit a trailing `/` line. The `/`
// is a SQL*Plus / SQLcl script terminator — it is NOT valid PL/SQL and
// the Oracle Go driver (go-ora) raises ORA-06550 when it encounters it
// via ExecContext. Both execution paths for these scaffolds —
// `app.App.AutoMigrate` (`sqlDB.Exec(up)`) and the file-based
// `Migrator` (`tx.Exec(script)`) — send the SQL straight to the driver,
// never through SQL*Plus, so the terminator must be omitted. This
// mirrors the no-`/` PL/SQL blocks in `pkg/db/migrate.go`'s
// `migrationsTableDDL` / `checksumsTableDDL`, which the driver accepts.
func writeOraclePLSQLBlock(b *strings.Builder, stmt, sqlcode, note string) {
	fmt.Fprintf(b, "BEGIN\n\tEXECUTE IMMEDIATE '%s';\nEXCEPTION\n\tWHEN OTHERS THEN\n\t\tIF SQLCODE != %s THEN RAISE; END IF; -- %s\nEND;\n",
		strings.ReplaceAll(stmt, "'", "''"),
		sqlcode,
		note,
	)
}

// oracleIdentifier renders an identifier for emission in scaffold DDL. Per
// ADR-011 the framework's Oracle strategy is UNQUOTED identifiers: Oracle
// folds an unquoted identifier to upper case at parse time, which is what the
// rest of the Oracle path expects — the CRUD layer (`pkg/model/crud.go`) emits
// bare identifiers, the migrations/checksums bootstrap (`pkg/db/migrate.go`)
// creates its tables unquoted, and introspection (`pkg/db/schema_drift.go`)
// matches via `UPPER(...)`. Quoting here (the pre-ADR-011 behaviour) created
// case-sensitive lower-case tables that those layers could not find.
//
// The identifier is emitted verbatim (callers pass values already validated by
// isValidIdentifierLike); Oracle does the case folding. This single choke point
// is also where conditional quoting would land if the reserved-word follow-up
// (a column named e.g. `comment`/`number`) is taken up.
func oracleIdentifier(value string) string {
	return value
}

func oracleTypeForField(f FieldMeta) string {
	base := strings.TrimPrefix(strings.TrimSpace(f.GoType), "*")
	switch strings.ToLower(base) {
	case "bool":
		return "NUMBER(1)"
	case "int", "int8", "int16", "int32", "uint", "uint8", "uint16", "uint32":
		return "NUMBER(10)"
	case "int64", "uint64":
		return "NUMBER(19)"
	case "float32":
		return "BINARY_FLOAT"
	case "float64":
		return "BINARY_DOUBLE"
	case "[]byte":
		return "BLOB"
	case "time.time":
		return "TIMESTAMP(6) WITH TIME ZONE"
	default:
		return "VARCHAR2(4000)"
	}
}

func oracleAutoIncrementPKType(goType string) bool {
	base := strings.TrimPrefix(strings.TrimSpace(goType), "*")
	switch strings.ToLower(base) {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
		return true
	default:
		return false
	}
}
